Feat/matching
nenber/StudeBuddy pull request #36
Opened 2021-01-21 11:50 UTC by nath026

Attention il y aura des conflits à s en occuper

2021-01-24 17:12 UTC, clee1999 commented
@nath026 branche good pour moi ! nickel !!

2021-01-30 02:22 UTC, Matx99 requested changes
- j'ai commenté du code à modifier
- la page de matching est accessible même sans être connecté (envoi d'erreur "Call to a member function getIsGodparent() on null"), il faut bloquer l'accès si on n'est pas connecté, ajouter : $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY'); 
- j'ai dû drop ma db et la recréer pour faire fonctionner l'update des entités...
- je tombe sur la page "Oups...

C'est un peu embarrassant mais y a personne qui correspond ton profil.
On t'invite modifier ton profile soit en changeant ton role ou bien en ajoutant des langues d'apprentissage. ", c'est normal ?

2021-01-30 02:22 UTC, Matx99 commented on app/src/Controller/UserController.php
> +            $this->addFlash('message', 'Profile mis à jour');
profil mis à jour*

2021-01-30 02:22 UTC, Matx99 commented on app/src/Controller/UserController.php
> +        $userMatchingLanguage = $subcribers = $buddies = array();
subscribers*?

2021-01-30 02:22 UTC, Matx99 commented on app/src/Controller/UserController.php
> +            $subcribers = $repository->findGodson(true);
subscribers*? (à chaque fois)

2021-01-30 02:22 UTC, Matx99 commented on app/src/Repository/UserRepository.php
> +    public function findByPatronage($patronage): array
en anglais only, findByBuddy? pareil pour tout le reste du code où il y a patronage

2021-01-30 02:22 UTC, Matx99 commented on app/templates/user/matching.html.twig
> +								<p>
Oups...

C'est un peu embarrassant mais y a personne qui correspond à ton profil.
On t'invite à modifier ton profil soit en changeant ton rôle ou bien en ajoutant des langues d'apprentissage.

2021-01-30 23:57 UTC, nath026 commented
check la PR de victor ca reprend cette PR

2021-01-30 23:57 UTC, closed without merging